// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwh573uY0_d-6flIBNEJdzingRJmpxNf8',
    appId: '1:634969588781:web:fb45fff18fc442433a24a4',
    messagingSenderId: '634969588781',
    projectId: 'hukuk-ofisim',
    authDomain: 'hukuk-ofisim.firebaseapp.com',
    storageBucket: 'hukuk-ofisim.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzyuWQ7FVAKJZozfdfltoLLNshYFpvNdw',
    appId: '1:634969588781:android:748d19033e33f7e33a24a4',
    messagingSenderId: '634969588781',
    projectId: 'hukuk-ofisim',
    storageBucket: 'hukuk-ofisim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0L2s_S3O-75qMvl9BPSMQd1jSiCnKGQI',
    appId: '1:634969588781:ios:8072ee3664eb58dd3a24a4',
    messagingSenderId: '634969588781',
    projectId: 'hukuk-ofisim',
    storageBucket: 'hukuk-ofisim.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0L2s_S3O-75qMvl9BPSMQd1jSiCnKGQI',
    appId: '1:634969588781:ios:8072ee3664eb58dd3a24a4',
    messagingSenderId: '634969588781',
    projectId: 'hukuk-ofisim',
    storageBucket: 'hukuk-ofisim.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwh573uY0_d-6flIBNEJdzingRJmpxNf8',
    appId: '1:634969588781:web:4eb62b5e7493a19c3a24a4',
    messagingSenderId: '634969588781',
    projectId: 'hukuk-ofisim',
    authDomain: 'hukuk-ofisim.firebaseapp.com',
    storageBucket: 'hukuk-ofisim.firebasestorage.app',
  );
}
